[build]
  publish = "public"
  command = "hugo --gc --config config-prod.toml"
  
[build.environment]
  HUGO_VERSION = "0.85.0"
  HUGO_THEME = "hugo-theme-massively"
  HUGO_BASEURL = "/"

[dev]
  framework = "hugo"
